export const Images = {
  home: require("./Home.png"),
  cart: require("./cart.png"),
  logo: require("./Logo.png"),
  shopBlue: require("./shopblue.png"),
  shopWhite: require("./shopwhite.png"),
  shopicon: require("./shopicon.png"),
  Make: require("./Make.png"),
  cartbtn: require("./cartbtn.png"),
  pastel: require("./pastel.png"),
  blue: require("./blue.png"),
  stawberry: require("./stawberry.png"),
  black: require("./black.png"),
  red: require("./red.png"),
  wodka: require("./wodka.png"),
  wiskey: require("./wiskey.png"),
  apple: require("./apple.png"),
  banana: require("./banaana.png"),
  pineaple: require("./pineaple.png"),
  mango: require("./mango.png"),
  back: require("./arrow.png"),
  copy: require("./copy.png"),
  save: require("./save.png"),
  share: require("./share.png"),
  main: require("./main.png"),
};
