import { StyleSheet } from "react-native";
export const checkoutstyle = StyleSheet.create({
  container: {
    backgroundColor: "#ffff",
    flex: 1,
    paddingHorizontal: 24,
  },
  backbtn: { height: 14, width: 14 },
  backbtnbg: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(0,0,0,0.6)",
    backgroundColor: "#ffff",
    shadowOpacity: 0.4,
    borderRadius: 10,
    elevation: 6,
  },
  checkouheading: {
    color: "#5A5A5C",
    fontSize: 15,
    fontFamily: "popins-medium",
    flex: 1,
    textAlign: "center",
  },
  Header: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  heading2: {
    fontFamily: "popins-semibold",
    fontSize: 16,
    textAlign: "center",
    color: "#323232",
    fontWeight: "500",
    marginVertical: 20,
  },
  box: {
    // justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  qrviewbox: {
    width: 270,
    justifyContent: "center",
    alignItems: "center",
  },
  uniqucode: {
    borderWidth: 1,
    borderColor: "#CCCCCC",
    paddingVertical: 20,
    width: "100%",
    marginVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 20,
    position: "relative",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  unitext: {
    fontSize: 14,
    color: "#03110A",
    fontWeight: "500",
  },
  orderhedaing: {
    position: "absolute",
    top: -10,
    left: 20,
    zIndex: 1,
    backgroundColor: "#ffff",
    color: "#5A5A5C",
    fontSize: 14,
    fontWeight: "500",
  },
  copimg: {
    width: 20,
    height: 24,
  },
  saveshare: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginVertical: 20,
  },

  imgbox: {
    width: 54,
    height: 54,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5F7FF",
    borderRadius: 10,
    marginHorizontal: 20,
  },
  imgsave: {
    width: 22,
    height: 22,
  },
});
