import { StyleSheet } from "react-native";
export const Shopstyle = StyleSheet.create({
  container: {
    paddingHorizontal: 24,
    backgroundColor: "#fff",
    marginTop: 0,
    padding: 0,
    // flex: 1,
  },
  logo: {
    width: 32,
    height: 32,
    marginVertical: 20,
  },
  ShopName: {
    fontSize: 16,
    fontFamily: "popins-light",
    fontWeight: "400",
    color: "#1C1E23",
  },
  Headings: {
    fontSize: 24,
    fontWeight: "600",
    fontFamily: "popins-semibold",
    color: "#4FB8E9",
  },
  change: {
    fontSize: 14,
    fontWeight: "400",
    fontFamily: "popins-regular",
    color: "#4FB8E9",
  },
  secondContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  makeContainer: {
    backgroundColor: "#4FB8E9",
    padding: 10,
    borderRadius: 10,
    flexDirection: "row",
    marginVertical: 20,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  Maketext: {
    fontFamily: "popins-bold",
    color: "#fff",
    fontSize: 16,
  },
  makeButton: {
    width: 91,
    height: 30,
    marginTop: 30,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
  },
  btnText: {
    color: "#4FB8E9",
    fontSize: 14,
    fontFamily: "popins-regular",
  },
  catheading: {
    fontFamily: "popins-bold",
    fontSize: 16,
    color: "#1C1E23",
  },
  catbutton: {
    backgroundColor: "white",
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 15,
    justifyContent: "center",
    alignContent: "center",
    shadowColor: "rgba(0,0,0,0.6)",
    shadowOpacity: 0.4,
    elevation: 6,
    marginHorizontal: 10,
    marginVertical: 5,
  },
  catbuttonHover: {
    backgroundColor: "#4FB8E9",
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 15,
    justifyContent: "center",
    alignContent: "center",
    shadowColor: "rgba(0,0,0,0.6)",
    shadowOpacity: 0.4,
    elevation: 6,
    marginHorizontal: 10,
    marginVertical: 5,
  },
  catBtnText: {
    fontSize: 14,
    fontFamily: "popins-regular",
    fontWeight: "600",
  },
  catBtnTextHover: {
    fontSize: 14,
    fontFamily: "popins-regular",
    fontWeight: "600",
    color: "white",
  },
});
